const defaultBanner = 'Vue.js - The Progressive JavaScript Framework'

// generated by the following code:
//
// require('gradient-string')([
//   { color: '#42d392', pos: 0 },
//   { color: '#42d392', pos: 0.1 },
//   { color: '#647eff', pos: 1 }
// ])('Vue.js - The Progressive JavaScript Framework'))
//
// Use the output directly here to keep the bundle small.
const gradientBanner =
  "\u001b[38;2;66;211;146mX\u001b[39m\u001b[38;2;66;211;146mo\u001b[39m\u001b[38;2;66;211;146md\u001b[39m\u001b[38;2;66;211;146me\u001b[39m\u001b[38;2;66;211;146ml\u001b[39m \u001b[38;2;67;208;149m-\u001b[39m \u001b[38;2;68;206;153mT\u001b[39m\u001b[38;2;69;203;156mh\u001b[39m\u001b[38;2;70;201;159me\u001b[39m \u001b[38;2;71;198;163mP\u001b[39m\u001b[38;2;72;196;166mr\u001b[39m\u001b[38;2;73;193;169mo\u001b[39m\u001b[38;2;74;190;172mg\u001b[39m\u001b[38;2;75;188;176mr\u001b[39m\u001b[38;2;76;185;179me\u001b[39m\u001b[38;2;77;183;182ms\u001b[39m\u001b[38;2;78;180;186ms\u001b[39m\u001b[38;2;79;178;189mi\u001b[39m\u001b[38;2;80;175;192mv\u001b[39m\u001b[38;2;81;172;196me\u001b[39m \u001b[38;2;82;170;199mO\u001b[39m\u001b[38;2;84;167;202mp\u001b[39m\u001b[38;2;85;165;205me\u001b[39m\u001b[38;2;86;162;209mn\u001b[39m\u001b[38;2;87;159;212mr\u001b[39m\u001b[38;2;88;157;215me\u001b[39m\u001b[38;2;89;154;219ms\u001b[39m\u001b[38;2;90;152;222mt\u001b[39m\u001b[38;2;91;149;225my\u001b[39m \u001b[38;2;92;147;229mF\u001b[39m\u001b[38;2;93;144;232mr\u001b[39m\u001b[38;2;94;141;235ma\u001b[39m\u001b[38;2;95;139;238mm\u001b[39m\u001b[38;2;96;136;242me\u001b[39m\u001b[38;2;97;134;245mw\u001b[39m\u001b[38;2;98;131;248mo\u001b[39m\u001b[38;2;99;129;252mr\u001b[39m\u001b[38;2;100;126;255mk\u001b[39m"

export { defaultBanner, gradientBanner }