const defaultBanner = 'create-xx - create a npm package that creates a npm package'

// generated by the following code:

// import gradient from 'gradient-string'
// console.log(JSON.stringify(gradient([
//   { color: '#42d392', pos: 0 },
//   { color: '#42d392', pos: 0.1 },
//   { color: '#647eff', pos: 1 },
// ])(defaultBanner)))

// Use the output directly here to keep the bundle small.
const gradientBanner =
"\u001b[38;2;66;211;146mc\u001b[39m\u001b[38;2;66;211;146mr\u001b[39m\u001b[38;2;66;211;146me\u001b[39m\u001b[38;2;66;211;146ma\u001b[39m\u001b[38;2;66;211;146mt\u001b[39m\u001b[38;2;66;211;146me\u001b[39m\u001b[38;2;67;209;149m-\u001b[39m\u001b[38;2;68;207;151mx\u001b[39m\u001b[38;2;68;205;154mx\u001b[39m \u001b[38;2;69;203;156m-\u001b[39m \u001b[38;2;70;201;159mc\u001b[39m\u001b[38;2;71;199;161mr\u001b[39m\u001b[38;2;72;197;164me\u001b[39m\u001b[38;2;72;195;166ma\u001b[39m\u001b[38;2;73;193;169mt\u001b[39m\u001b[38;2;74;191;171me\u001b[39m \u001b[38;2;75;189;174ma\u001b[39m \u001b[38;2;75;187;176mn\u001b[39m\u001b[38;2;76;185;179mp\u001b[39m\u001b[38;2;77;183;181mm\u001b[39m \u001b[38;2;78;181;184mp\u001b[39m\u001b[38;2;79;179;187ma\u001b[39m\u001b[38;2;79;177;189mc\u001b[39m\u001b[38;2;80;175;192mk\u001b[39m\u001b[38;2;81;173;194ma\u001b[39m\u001b[38;2;82;171;197mg\u001b[39m\u001b[38;2;83;169;199me\u001b[39m \u001b[38;2;83;168;202mt\u001b[39m\u001b[38;2;84;166;204mh\u001b[39m\u001b[38;2;85;164;207ma\u001b[39m\u001b[38;2;86;162;209mt\u001b[39m \u001b[38;2;87;160;212mc\u001b[39m\u001b[38;2;87;158;214mr\u001b[39m\u001b[38;2;88;156;217me\u001b[39m\u001b[38;2;89;154;220ma\u001b[39m\u001b[38;2;90;152;222mt\u001b[39m\u001b[38;2;91;150;225me\u001b[39m\u001b[38;2;91;148;227ms\u001b[39m \u001b[38;2;92;146;230ma\u001b[39m \u001b[38;2;93;144;232mn\u001b[39m\u001b[38;2;94;142;235mp\u001b[39m\u001b[38;2;94;140;237mm\u001b[39m \u001b[38;2;95;138;240mp\u001b[39m\u001b[38;2;96;136;242ma\u001b[39m\u001b[38;2;97;134;245mc\u001b[39m\u001b[38;2;98;132;247mk\u001b[39m\u001b[38;2;98;130;250ma\u001b[39m\u001b[38;2;99;128;252mg\u001b[39m\u001b[38;2;100;126;255me\u001b[39m"

export { defaultBanner, gradientBanner }